version: 2.1
orbs:
  ruby: circleci/ruby@2.1.1

jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.1
        environment:
          BUNDLE_VERSION=2.1.4
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Install Bundler
          command: gem install bundler:2.1.4
      - run:
          name: Bundle install
          command: bundle install
      - run:
          name: Run linters
          command: bundle exec rubocop
      - run:
          name: Run spec
          command: bundle exec rake spec
